# Generated by Django 2.1.2 on 2018-11-04 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examid', models.CharField(max_length=40)),
                ('examname', models.CharField(max_length=40)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eadmin.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='enrollments',
            name='courseid',
        ),
        migrations.RemoveField(
            model_name='enrollments',
            name='roll_no',
        ),
        migrations.DeleteModel(
            name='Enrollments',
        ),
    ]
