# Generated by Django 2.1.2 on 2018-11-04 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_applicant'),
        ('eadmin', '0002_auto_20181104_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('paymentref', models.FileField(upload_to='')),
                ('hallticket', models.FileField(upload_to='')),
                ('examid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eadmin.Exam')),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Applicant')),
            ],
        ),
    ]
