# Generated by Django 2.1.2 on 2018-11-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0006_auto_20181105_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollments',
            name='examid',
            field=models.CharField(max_length=40),
        ),
    ]
