# Generated by Django 2.1.2 on 2018-11-05 13:04

from django.db import migrations, models
import eadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0007_auto_20181105_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollments',
            name='paymentref',
            field=models.FileField(upload_to=eadmin.models.content_file_name),
        ),
    ]
