# Generated by Django 2.1.2 on 2018-11-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0008_auto_20181105_1834'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollments',
            unique_together=set(),
        ),
    ]
