# Generated by Django 2.1.2 on 2018-11-09 13:31

from django.db import migrations, models
import eadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0010_auto_20181105_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='examinerid',
            field=models.CharField(default='02', max_length=40),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='paymentref',
            field=models.FileField(upload_to=eadmin.models.content_file_name),
        ),
    ]
