# Generated by Django 2.1.2 on 2018-11-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0011_auto_20181109_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollments',
            name='hallticket',
        ),
    ]
