# Generated by Django 2.1.2 on 2018-11-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0013_auto_20181111_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='examinerid',
            field=models.CharField(default='02', max_length=50),
        ),
    ]
