# Generated by Django 2.1.2 on 2018-11-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0014_course_examinerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='examinerid',
        ),
    ]
