# Generated by Django 2.1.2 on 2018-10-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=13)),
            ],
        ),
    ]
