# Generated by Django 2.1.2 on 2018-10-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_admin_examiner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
