# Generated by Django 2.1.2 on 2018-10-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_applicant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
