# Generated by Django 2.1.2 on 2018-10-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('roll_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=13)),
            ],
        ),
    ]
