# Generated by Django 2.1.2 on 2018-10-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
