# Generated by Django 2.1.2 on 2018-11-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='examid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='results',
            name='roll_no',
            field=models.CharField(max_length=10),
        ),
    ]
