# Generated by Django 2.1.2 on 2018-11-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0009_auto_20181122_2148'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='results',
            unique_together={('examid', 'roll_no')},
        ),
    ]
