# Generated by Django 2.1.2 on 2018-11-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0011_auto_20181122_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examid', models.CharField(max_length=5)),
                ('qid', models.CharField(max_length=5, unique=True)),
                ('q', models.TextField(unique=True)),
                ('opta', models.TextField()),
                ('optb', models.TextField()),
                ('optc', models.TextField()),
                ('optd', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examid', models.CharField(max_length=5)),
                ('studid', models.CharField(max_length=5)),
                ('reponse', models.CharField(max_length=500)),
                ('cor', models.CharField(max_length=2)),
                ('wrg', models.CharField(max_length=2)),
                ('una', models.CharField(max_length=2)),
                ('total', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='responses',
            unique_together={('studid', 'examid')},
        ),
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together={('qid', 'examid')},
        ),
    ]
