# Generated by Django 2.1.2 on 2018-11-26 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0012_auto_20181126_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Applicant'),
        ),
    ]
